server:
  port: 8001
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mariadb://localhost:3306/bang_video
    username: video
    password: kkskkksk
    driver-class-name: org.mariadb.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    redis:
      host: localhost
      port: 6379