services:
  nacos:
    networks:
      - bang-video
    image: nacos/nacos-server:v2.5.1
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      - MODE=standalone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    networks:
      - bang-video
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    networks:
      - bang-video
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    networks:
      - bang-video
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/nginx:latest
    ports:
      - "7002:80"
    volumes:
      - statics:/usr/share/nginx/html

  rabbitmq:
    networks:
      - bang-video
    image: rabbitmq:4.1-rc
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://guest:guest@localhost:15672/api/healthchecks/node"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  elasticsearch:
    networks:
      - bang-video
    image: elasticsearch:8.17.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins

  gateway:
    networks:
      - bang-video
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/gateway:latest
    ports:
      - "7001:7001"
    environment:
      - SERVER_PORT=7001
      - NACOS_SERVER=nacos:8848
    depends_on:
      nacos:
        condition: service_healthy

  user:
    networks:
      - bang-video
    build:
      context: ./user
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/user:latest
    ports:
      - "8001:8001"
    environment:
      - SERVER_PORT=8001
      - NACOS_SERVER=nacos:8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - STATIC_SERVER=http://localhost:7002
    depends_on:
      nacos:
        condition: service_healthy

  video:
    networks:
      - bang-video
    build:
      context: ./video
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/video:latest
    ports:
      - "8002:8002"
    environment:
      - SERVER_PORT=8002
      - NACOS_SERVER=nacos:8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=video
      - ELASTICSEARCH_PASSWORD=kkskkksk
      - STATIC_SERVER=http://localhost:7002
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      nacos:
        condition: service_healthy

  community:
    networks:
      - bang-video
    build:
      context: ./community
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/community:latest
    ports:
      - "8003:8003"
    environment:
      - SERVER_PORT=8003
      - NACOS_SERVER=nacos:8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      nacos:
        condition: service_healthy

  file:
    networks:
      - bang-video
    build:
      context: ./file
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/file:latest
    ports:
      - "8004:8004"
    environment:
      - SERVER_PORT=8004
      - NACOS_SERVER=nacos:8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - statics:/static

  encoding:
    networks:
      - bang-video
    build:
      context: ./encoding
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/encoding:latest
    ports:
      - "8005:8005"
    environment:
      - SERVER_PORT=8005
      - NACOS_SERVER=nacos:8848
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - statics:/static

  audit-video:
    networks:
      - bang-video
    build:
      context: ./audit-video
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/audit-video:latest
    ports:
      - "8006:8006"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      nacos:
        condition: service_healthy
    volumes:
      - statics:/static

volumes:
  redis_data:
  mongodb_data:
  es_data:
  es_plugins:
  statics:

networks:
  bang-video:
    driver: bridge