services:
  redis:
    networks:
      - bang-video
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    networks:
      - bang-video
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    networks:
      - bang-video
    image: rabbitmq:4.1-rc
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 20

  nginx:
    networks:
      - bang-video
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/nginx:latest
    ports:
      - "7002:80"
    volumes:
      - statics:/usr/share/nginx/html

  elasticsearch:
    networks:
      - bang-video
    image: elasticsearch:8.17.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_plugins:/usr/share/elasticsearch/plugins

  eureka:
    networks:
      - bang-video
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/eureka:latest
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/"]
      interval: 5s
      timeout: 5s
      retries: 20

  gateway:
    networks:
      - bang-video
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/gateway:latest
    ports:
      - "7001:7001"
    environment:
      - SERVER_PORT=7001
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000
    depends_on:
      eureka:
        condition: service_healthy

  user:
    networks:
      - bang-video
    build:
      context: ./user
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/user:latest
    environment:
      - SERVER_PORT=8001
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - STATIC_SERVER=http://localhost:7002
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  video:
    networks:
      - bang-video
    build:
      context: ./video
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/video:latest
    environment:
      - SERVER_PORT=8002
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_USERNAME=video
      - ELASTICSEARCH_PASSWORD=kkskkksk
      - STATIC_SERVER=http://localhost:7002
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  community:
    networks:
      - bang-video
    build:
      context: ./community
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/community:latest
    environment:
      - SERVER_PORT=8003
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  file:
    networks:
      - bang-video
    build:
      context: ./file
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/file:latest
    environment:
      - SERVER_PORT=8004
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      eureka:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - statics:/static

  encoding:
    networks:
      - bang-video
    build:
      context: ./encoding
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/encoding:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - statics:/static

  audit-video:
    networks:
      - bang-video
    build:
      context: ./audit-video
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/audit-video:latest
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - statics:/static

volumes:
  redis_data:
  mongodb_data:
  es_data:
  es_plugins:
  statics:

networks:
  bang-video:
    driver: bridge