services:
  redis:
    networks:
      - bang-video
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    networks:
      - bang-video
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    networks:
      - bang-video
    image: rabbitmq:4.1-rc
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://guest:guest@localhost:15672/api/healthchecks/node"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  eureka:
    networks:
      - bang-video
    build:
      context: ./eureka
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/eureka:latest
    ports:
      - "7000:7000"

  gateway:
    networks:
      - bang-video
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/gateway:latest
    ports:
      - "7001:7001"
    environment:
      - SERVER_PORT=7001
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000

  community:
    networks:
      - bang-video
    build:
      context: ./community
      dockerfile: Dockerfile
    image: localhost:5000/bang-video/community:latest
    ports:
      - "8003:8003"
    environment:
      - SERVER_PORT=8003
      - EUREKA_HOST=eureka
      - EUREKA_PORT=7000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_USER=root
      - MONGODB_PASSWORD=password
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - SPRING_AMQP_DESERIALIZATION_TRUST_ALL=true

volumes:
  redis_data:
  mongodb_data:
  es_data:
  es_plugins:
  statics:

networks:
  bang-video:
    driver: bridge