server:
  port: ${SERVER_PORT:8004}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:7000}/eureka/
spring:
  application:
    name: file-service
  cloud:
    refresh:
      enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB