server:
  port: ${SERVER_PORT:8004}
spring:
  application:
    name: file-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB