server:
  port: 8002
spring:
  application:
    name: video-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      host: localhost
      port: 27017
      username: video
      password: kkskkksk
      database: BangVideo