server:
  port: ${SERVER_PORT:7001}
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:7000}/eureka/
spring:
  application:
    name: gateway
  cloud:
    refresh:
      enabled: false
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "http://*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: video-service
          uri: lb://video-service
          predicates:
            - Path=/video/**
          filters:
            - StripPrefix=1
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
          filters:
            - StripPrefix=1
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1