server:
  port: 7000
spring:
  application:
    name: eureka
  cloud:
    refresh:
      enabled: false
  main:
    allow-circular-references: true
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: true

logging:
  level:
    org.springframework.web.servlet.mvc:
      method.annotation.RequestMappingHandlerMapping: trace
    com.netflix: warn