apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: xpack.security.http.ssl.enabled
              value: "false"
          image: elasticsearch:8.17.3
          name: elasticsearch
          ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
            - mountPath: /usr/share/elasticsearch/plugins
              name: es-plugins
      restartPolicy: Always
      volumes:
        - name: es-data
          persistentVolumeClaim:
            claimName: es-data
        - name: es-plugins
          persistentVolumeClaim:
            claimName: es-plugins
