apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway
  template:
    metadata:
      annotations:
        kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: gateway
    spec:
      containers:
        - env:
            - name: NACOS_SERVER
              value: nacos:8848
            - name: SERVER_PORT
              value: "7001"
          image: localhost:5000/bang-video/gateway:latest
          name: gateway
          ports:
            - containerPort: 7001
              protocol: TCP
      initContainers:
        - name: wait
          image: curlimages/curl
          command: [ 'sh', '-c', 'until curl -s http://nacos:8848/nacos/health; do sleep 2; done' ]

      restartPolicy: Always
