apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: gateway
  name: gateway
spec:
  type: NodePort
  ports:
    - name: "7001"
      port: 7001
      targetPort: 7001
      nodePort: 30001
  selector:
    io.kompose.service: gateway
