apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nacos
  name: nacos
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nacos
  template:
    metadata:
      annotations:
        kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: nacos
    spec:
      containers:
        - env:
            - name: MODE
              value: standalone
          image: nacos/nacos-server:v2.5.1
          readinessProbe:
            tcpSocket:
              port: 8848
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          name: nacos
          ports:
            - containerPort: 8848
              protocol: TCP
            - containerPort: 9848
              protocol: TCP
            - containerPort: 9849
              protocol: TCP
      restartPolicy: Always
