apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nacos
  name: nacos
spec:
  ports:
    - name: "8848"
      port: 8848
      targetPort: 8848
    - name: "9848"
      port: 9848
      targetPort: 9848
    - name: "9849"
      port: 9849
      targetPort: 9849
  selector:
    io.kompose.service: nacos
