apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: statics
  name: statics
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
