apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  template:
    metadata:
      annotations:
        kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: user
    spec:
      containers:
        - env:
            - name: NACOS_SERVER
              value: nacos:8848
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "8001"
            - name: STATIC_SERVER
              value: http://localhost:7002
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USER
              value: root
            - name: MONGODB_PASSWORD
              value: password
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          image: localhost:5000/bang-video/user:latest
          name: user
          ports:
            - containerPort: 8001
              protocol: TCP
      initContainers:
        - name: wait
          image: curlimages/curl
          command: [ 'sh', '-c', 'until curl -s http://nacos:8848/nacos/health; do sleep 2; done' ]
      restartPolicy: Always
