apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: video
  name: video
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: video
  template:
    metadata:
      annotations:
        kompose.cmd: D:\bin\kompose.exe convert -o .\kubernetes\
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: video
    spec:
      containers:
        - env:
            - name: ELASTICSEARCH_HOST
              value: elasticsearch
            - name: ELASTICSEARCH_PASSWORD
              value: kkskkksk
            - name: ELASTICSEARCH_PORT
              value: "9200"
            - name: ELASTICSEARCH_USERNAME
              value: video
            - name: MONGODB_HOST
              value: mongodb
            - name: MONGODB_PASSWORD
              value: password
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_USER
              value: root
            - name: NACOS_SERVER
              value: nacos:8848
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: SERVER_PORT
              value: "8002"
            - name: SPRING_AMQP_DESERIALIZATION_TRUST_ALL
              value: "true"
            - name: STATIC_SERVER
              value: http://localhost:7002
          image: localhost:5000/bang-video/video:latest
          name: video
          ports:
            - containerPort: 8002
              protocol: TCP
      initContainers:
        - name: wait
          image: curlimages/curl
          command: [ 'sh', '-c', 'until curl -s http://nacos:8848/nacos/health; do sleep 2; done' ]
      restartPolicy: Always
