name: Test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: '21'

      - name: Grant permission
        run: chmod -R 777 *

      - name: Init gradle
        run: ./gradlew clean

      - name: Build
        run: ./gradlew build -x test