name: Test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: debian:bullseye
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Gradle plugin
        run: ./gradlew nativeCompile

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: user
          path: user/build/native/nativeCompile/*

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: video
          path: video/build/native/nativeCompile/*

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: community
          path: community/build/native/nativeCompile/*

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: file
          path: file/build/native/nativeCompile/*

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: encoding
          path: encoding/build/native/nativeCompile/*