name: Test
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: chmod -R 777 *
        run: chmod -R 777 *

      - name: Gradle plugin
        run: ./gradlew nativeCompile